# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 732f8ac
_src_path: /home/sdowney/src/example/main/
include_prefix: smd
library_name: transpose
maintainer_email: sdowney@gmail.com
maintainer_name: Steve Downey
namespace: transpose
project_slug: transpose
project_title: Transpose Contexts
sample_value: Steve
