#!/usr/bin/env python3

# papers/wg21/filters/transclude.py
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# Splices generated wording fragments into a paper.
#
# A fenced div carrying the `include` class is replaced by the parsed blocks of
# the file it names:
#
#     ::: {.include file="wording/transpose.applicative.syn.md"}
#     :::
#
# The fragments under `wording/` are generated by `make wording`, which runs
# beman.specgen over the marked-up headers. Splicing them here -- before
# citeproc and wg21.py -- means the `[x]{.pnum}` and `[stable.name]{- .sref}`
# spans inside a fragment reach the wg21 filter exactly as if they had been
# typed into the paper.
#
# Paths are resolved against $TRANSCLUDE_BASE when set, and otherwise against
# the working directory, which the Makefile fixes at the paper source
# directory.

import os
import sys

import panflute as pf

MAX_DEPTH = 4

BASE = os.environ.get("TRANSCLUDE_BASE") or os.getcwd()


def fail(message):
    sys.stderr.write("transclude.py: error: {}\n".format(message))
    sys.exit(1)


def expand(path, depth):
    """Parse `path` and return its blocks, with nested includes expanded."""
    if depth > MAX_DEPTH:
        fail("include nesting deeper than {} at `{}'".format(MAX_DEPTH, path))

    resolved = path if os.path.isabs(path) else os.path.join(BASE, path)
    try:
        with open(resolved, encoding="utf-8") as stream:
            text = stream.read()
    except OSError as error:
        fail("cannot read `{}': {}".format(resolved, error))

    blocks = pf.convert_text(text, input_format="markdown")
    return [
        block
        for element in blocks
        for block in walk(element, depth + 1)
    ]


def walk(element, depth):
    """Return `element` as a block list, expanding any includes inside it."""
    included = include_target(element)
    if included is not None:
        return expand(included, depth)
    element.walk(lambda child, doc: action(child, doc, depth))
    return [element]


def include_target(element):
    """The file an include div names, or None if `element` is not one."""
    if not isinstance(element, pf.Div) or "include" not in element.classes:
        return None
    target = element.attributes.get("file")
    if not target:
        fail("`::: include' div has no `file' attribute")
    return target


def action(element, doc, depth=0):
    target = include_target(element)
    if target is None:
        return None
    return expand(target, depth + 1)


def main(doc=None):
    return pf.run_filter(action, doc=doc)


if __name__ == "__main__":
    main()
